[build]
target = "aarch64-linux-android"

[target.aarch64-linux-android.test_ndk] # `links` build script override
rustc-link-lib = ["frida-gum"]
rustc-link-search = ["../c"]
rustc-flags = "-L ../c"

[env]
C_INCLUDE_PATH="$C_INCLUDE_PATH:/home/fang/workspace/dev/rust/test_ndk/c"
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/fang/workspace/dev/rust/test_ndk/c"
BINDGEN_EXTRA_CLANG_ARGS='--sysroot /home/fang/.cargo/NDK/arm64/sysroot'